# Generated by Django 4.2.7 on 2023-12-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('preco', models.FloatField()),
                ('condicao', models.CharField(blank=True, choices=[('Corte', 'Corte'), ('Despolpar', 'Despolpar')], max_length=20, null=True)),
            ],
        ),
    ]
