# Generated by Django 4.2.7 on 2024-01-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_compra_espaco_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueFruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.IntegerField()),
            ],
        ),
    ]
