# Generated by Django 4.2.7 on 2024-01-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_compra_estoque_estoquefruta_quantidade_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produzida', models.FloatField()),
                ('data_producao', models.DateTimeField(auto_now_add=True)),
                ('quantidade_reduzida', models.IntegerField()),
                ('estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.estoquefruta')),
                ('fruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.fruta')),
            ],
        ),
    ]
