# Generated by Django 4.2.7 on 2024-01-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_producao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoquePolpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.IntegerField()),
                ('quantidade_max', models.FloatField(default=1000)),
            ],
        ),
    ]
