# Generated by Django 4.2.7 on 2024-02-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
