# Generated by Django 4.2.7 on 2024-07-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipoUsuario',
            field=models.CharField(blank=True, choices=[('gerente', 'gerente'), ('entregador', 'entregador'), ('tec_de_alimentos', 'tec_de_alimentos'), ('ger_de_producao', 'ger_de_producao'), ('aux_de_producao', 'aux_de_producao')], max_length=20, null=True),
        ),
    ]
